#!/usr/bin/env python
import click
import subprocess
import socket


def get_current_ip():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("8.8.8.8", 80))
    current_ip = s.getsockname()[0]
    s.close()
    return current_ip


def domain_exists(domain):
    args = ['plesk', 'bin', 'domain', '--info']
    args.append(domain)
    result = subprocess.run(args, capture_output=True)
    if result.returncode == 0:
        return True
    else:
        return False


def run_command(command_array):
    command_string = ' '.join(command_array)
    return subprocess.run(command_array, capture_output=True)


@click.group()
def cli():
    pass


@cli.group()
def domain():
    pass


@domain.command('create')
@click.option('--domain', prompt=True, help='Domain name')
@click.option('--hosting', prompt=True, help='Enable hosting', type=click.Choice(['yes', 'no']))
def domain_create(domain, hosting):
    if domain_exists(domain):
        click.echo('Domain already exists')
        return
    args = ['plesk', 'bin', 'domain', '--create']
    hostingcommand = ['plesk', 'bin', 'site', '--update', domain, '-hosting true']
    args.append(domain)

    click.echo('Creating domain...')
    result = run_command(args)
    created = False
    if result.returncode == 0:
        click.echo('Domain created successfully')
        created = True
    else:
        click.echo('Error creating domain')
        click.echo(result.stderr.decode('utf-8'))

    if created and hosting == 'yes':
        click.echo('Enabling hosting...')
        result = run_command(hostingcommand)
        if result.returncode == 0:
            click.echo('Hosting enabled successfully')
        else:
            click.echo('Error enabling hosting')
            click.echo(result.stderr.decode('utf-8'))


@domain.command('delete')
@click.option('--domain', prompt=True, help='Domain name')
def domain_delete(domain):
    if not domain_exists(domain):
        click.echo('Domain does not exist')
        return

    sure = click.confirm('Are you sure you want to delete the domain?')
    if not sure:
        return
    args = ['plesk', 'bin', 'domain', '--remove']
    args.append(domain)

    click.echo('Deleting domain...')
    result = run_command(args)
    if result.returncode == 0:
        click.echo('Domain deleted successfully')
    else:
        click.echo('Error deleting domain')
        click.echo(result.stderr.decode('utf-8'))


# start cli on call
if __name__ == "__main__":
    cli();
