#!/usr/bin/env python
import os

import click
import subprocess
import socket


def get_current_ip():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("8.8.8.8", 80))
    current_ip = s.getsockname()[0]
    s.close()
    return current_ip


def domain_exists(domain):
    args = ['plesk', 'bin', 'domain', '--info']
    args.append(domain)
    result = subprocess.run(args, capture_output=True)
    if result.returncode == 0:
        return True
    else:
        return False


def run_command(command_array):
    command_string = ' '.join(command_array)
    return os.system(command_string)


@click.group()
def cli():
    pass


@cli.group()
def domain():
    pass


@domain.command('create')
@click.option('--domain', prompt=True, help='Domain name')
@click.option('--hosting', prompt=True, help='Enable hosting', type=click.Choice(['yes', 'no']))
def domain_create(domain, hosting):
    if domain_exists(domain):
        click.echo('Domain already exists')
        return
    args = ['/usr/local/psa/bin/subscription', '--create']
    args.append(domain)

    if(hosting == 'yes'):
        args.append('-hosting true')
        args.append('-ip ' + get_current_ip())
        user = click.prompt('Enter username')
        args.append('-login ' + user)
        password = click.prompt('Enter password', hide_input=True)
        args.append('-passwd ' + password)

    click.echo('Creating domain...')
    result = run_command(args)
    if result.returncode == 0:
        click.echo('Domain created successfully')
    else:
        click.echo('Error creating domain')
        click.echo(result.stderr.decode('utf-8'))


@domain.command('delete')
@click.option('--domain', prompt=True, help='Domain name')
def domain_delete(domain):
    if not domain_exists(domain):
        click.echo('Domain does not exist')
        return

    sure = click.confirm('Are you sure you want to delete the domain?')
    if not sure:
        return
    args = ['plesk', 'bin', 'domain', '--remove']
    args.append(domain)

    click.echo('Deleting domain...')
    result = run_command(args)
    if result.returncode == 0:
        click.echo('Domain deleted successfully')
    else:
        click.echo('Error deleting domain')
        click.echo(result.stderr.decode('utf-8'))


# start cli on call
if __name__ == "__main__":
    cli();
